package iplCricketGame;

public enum  SortField {
    AVERAGE, STRIKE_RATE, NO_OF_4S_AND_6S,STRIKE_RATE_WITH_6S_4S,PLAYER_NAME
    ,GREAT_STRIKE_RATE_AND_BEST_AVG,ECONOMY_RATE,BEST_RUNS_WITH_BEST_AVG,STRIKE_RATE_WITH_4_AND_5_WICKET
    ,BEST_BOWLING_AVG_WITH_BEST_STRIKE_RATE,MAX_WICKETS_WITH_BEST_BOWLING_AVERAGE;
}
